image: python:3.11

stages:
  - lint
  - test
  - build

# Base template for Python jobs
before_script:
  - python --version
  #- apt-get update && apt-get install libgl1 -Y
  - pip install -r requirements.txt
  - pip install pylint
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest-qt
  #- pip install keyboard
  #- pip install psutil
  - pip install pyinstaller
  - echo ${!CI_PROJECT_DIR}

# Linting jobs
pylint:
  stage: lint
  allow_failure: true
  script:
    - pylint ${CI_PROJECT_DIR}/QUEST/
    - pylint ${CI_PROJECT_DIR}/Tools/

# Testing jobs
test:
  stage: test
  allow_failure: true
  script:
    - pytest ${CI_PROJECT_DIR}/tests/ -sv

build:
  stage: build
  script: 
    - pyinstaller ${CI_PROJECT_DIR}/QUEST/Launcher.py --onefile --paths ${CI_PROJECT_DIR} 
  artifacts:
    paths:
        - dist/Launcher.exe