image: python:3.11

stages:
  - lint
  - test
  - build

# Base template for Python jobs
before_script:
  - apt install libegl1
  - python --version
  - pip install -r requirements.txt
  - pip install pylint
  - pip install pytest
  - pip install pyinstaller

# Linting jobs
pylint:
  stage: lint
  allow_failure: true
  script:
    - pylint ${CI_PROJECT_DIR}/QUEST/
    - pylint ${CI_PROJECT_DIR}/Tools/

# Testing jobs
test:
  stage: test
  allow_failure: true
  script:
    - pytest ${CI_PROJECT_DIR}/tests/ -sv

build:
  stage: build
  script: 
    - pyinstaller ${CI_PROJECT_DIR}/QUEST/Launcher.py --onefile --paths ${CI_PROJECT_DIR} 
  artifacts:
    paths:
        - ls -R
        - ${CI_PROJECT_DIR}/dist/Launcher.exe