#image: python:3.11
image: tobix/pywine:3.11

stages:
  - lint
  - test
  - build

# Base template for Python jobs
before_script:
  - . /opt/mkuserwineprefix
  - wine python --version
  #- apt-get update && apt-get install libgl1 -Y
  - wine python -m pip install -r requirements.txt
  - wine python -m pip install pylint
  - wine python -m pip install pytest
  - wine python -m pip install pytest-cov
  - wine python -m pip install pytest-qt
  #- pip install keyboard
  #- pip install psutil
  - wine python -m pip install pyinstaller
  #- echo ${CI_PROJECT_DIR}

# Linting jobs
pylint:
  stage: lint
  allow_failure: true
  script:
    - wine python -m pylint ${CI_PROJECT_DIR}/QUEST/
    - wine python -m pylint ${CI_PROJECT_DIR}/Tools/

# Testing jobs
test:
  stage: test
  allow_failure: true
  script:
    - wine python -m pytest ${CI_PROJECT_DIR}/tests/ -sv

build:
  stage: build
  script: 
    - wine /opt/wineprefix/drive_c/Python311/Scripts/pyinstaller.exe ${CI_PROJECT_DIR}/QUEST/Launcher.py --onefile --paths ${CI_PROJECT_DIR} 
  artifacts:
    paths:
        - "dist/*.exe"