image: python:3.11

stages:
  - lint
  - test
  - build

# Base template for Python jobs
before_script:
  - python --version
  - pip install -r requirements.txt
  - pip install pylint
  - pip install pytest
  - pip install pyinstaller

# Linting jobs
black:
  stage: lint
  allow_failure: true
  script:
    - black --check ${CI_PROJECT_DIR}

isort:
  stage: lint
  allow_failure: true
  script:
    - isort --check-only ${CI_PROJECT_DIR}

flake8:
  stage: lint
  allow_failure: true
  script:
    - flake8 ${CI_PROJECT_DIR}

pylint:
  stage: lint
  allow_failure: true
  script:
    - pylint ${CI_PROJECT_DIR}

mypy:
  stage: lint
  allow_failure: true
  script:
    - mypy ${CI_PROJECT_DIR}

# Testing jobs
test:
  stage: test
  allow_failure: true
  script:
    - pytest ${CI_PROJECT_DIR}\tests\ -sv

build:
  stage: build
  script: 
    - pyinstaller ${CI_PROJECT_DIR}\QUEST\Launcher.py --onefile --paths ${CI_PROJECT_DIR} 
  artifacts:
    paths:
        - ${CI_PROJECT_DIR}\dist\Launcher.exe