stages:
    - build
    - test

create_badge_svg:
  stage: build
  image: python:latest
  tags:
    - docker
  script:
    - echo "Python other dependencies installation"
  after_script:
    - pip install anybadge
    - commits=$(git rev-list --all --count)
    - anybadge -l commits -v $commits -f commits.svg -c green
  artifacts:
    paths:
        - commits.svg
    when: always
    expire_in: 4 weeks

run tests:
  stage: test
  image: python:3.9
  script:
    - pip install pytest pytest-cov
    - coverage run -m pytest #--source=test
    - coverage report
    - coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml
