[tool.pylint.main]
jobs = 0
load-plugins = [
  # custom plugins
]

[tool.pylint.messages_control]
disable = ["C0301", "C0302", "C0103", "E0611", "R0801", "W1514", "R0912", "R0913", "R0914", "R0915", "R0916", "R0917", "R1702", "E0611", "R0902", "R0903", "E0401", "W0511", "I1101", "W0640", "C0411", "E1101", "W0611"]
enable = [
  # custom plugins
]

[tool.pylint.reports]
score = "no"