""" Info for questionnaire editor
    This includes:
    - which fields exist
    - default values, if needed
    - which fields apply to which question type
"""

tooltips = {
    "id": "The id for this question. Has to be unique.",
    "type": "The basic type of the question/element.",
    "required": "Check this if an answer is required for this question.",
    "buttons": "Choose which buttons should be used.",
    "start_cue": "The cue/marker in the audio software to start playing at.",
    "end_cue": "The cue/marker in the audio software to stop playing at. (optional)",
    "track": "The tack(s) that should be unmuted for playback.",
    "video": "Path to the video file. (optional)",
    "start_cues": "List of starting points for MUSHRA playback. [Ref, Cue1, Cue2,...]",
    "end_cues": "List of ending points for MUSHRA playback. [Ref, Cue1, Cue2,...] (optional)",
    "text": "The text of the question.",
    "answers": "A comma separated list of answer possibilities.",
    "size": "1 for single line text field, >1 for multi line",
    "policy": "either \"int\", min, max or \"double\", min, max, decimals or \"regexp\", expression (optional)",
    "min": "minimal value",
    "max": "maximal value",
    "start": "default position of slider handle",
    "labelled": "Check if you want ticks to be labelled",
    "label": "If labelled, list of tick labels",
    "question_above": "If checked, question text is displayed above the slider.",
    "header": "Adds a row above the slider with specified labels.",
    "objectName": "Give this question a specific name that you can reference in the stylesheet to make it look unique.",
    "title": "Main title of the page, displayed at the top",
    "description": "Put further instructions/descriptions for the page here; is displayed at the top of the page, under the title. (optional)",
    "audio_ip": "The network-address of the audio software (REAPER) to use. Leave blank for none.",
    "audio_port": "The network-port of the audio software (REAPER) to use. Leave blank for none.",
    "audio_tracks": "The number of total tracks in the (REAPER-) project used. Leave blank for none.",
    "video_ip": "The network-address of the video software to use. Leave blank for none.",
    "video_port": "The network-port of the video software to use. Leave blank for none.",
    "pupil_ip": "The network-address of Pupil Core. Leave blank if not used.",
    "pupil_port": "The network-port of Pupil Core. Leave blank if not used.",
    "help_ip": "The network-address of the pc listening to help requests from the participant. Leave blank if not used.",
    "help_port": "The network-port of the pc listening to help requests from the participant. Leave blank if not used.",
    "help_text": "The text of the help request button.",
    "go_back": "Enable if the participants are allowed to navigate back through the questionnaire.",
    "back_text": "The text displayed on the backward button, if present.",
    "forward_text": "The text on the forward button.",
    "send_text": "The text to display on the forward button when the last page is reached.",
    "answer_pos": "Text on the positive-answer-button in the confirm-save dialog.",
    "answer_neg": "Text on the negative-answer-button in the confirm-save dialog.",
    "save_message": "Text of the confirm-save dialog.",
    "pagecount_text": "Text displaying the number of the current page. Use {} as placeholder for the actual number.",
    "filepath_results": "Path to the destination/csv-file which the results should be saved to.",
    "delimiter": "Delimiter to use for the csv-file.",
    "stylesheet": "Path to the stylesheet file to use.",
    "inscription": "Text to display on the button.",
    "function": "Functionality of the button.",
    "randomgroup": "If you wish to display certain pages in a randomized order per participant, give them the same group. (optional)",
    "xfade": "If all conditions use the same markers this will allow the option for a smoother transition between them.",
    "pupil": "When filled sends a annotation to Pupil Capture, when the Play Button is clicked.",
    "timer": "Time in milliseconds until objects below should be hidden after activating the button. (optional)",
    "password_file": "Path to a line-break separated list of valid passwords.",
    "button_texts": "The texts to display on the ABX test's play buttons. (optional, default: A, B(, X))",
    "x": "If checked, the first entry in start_cues/tracks is chosen as reference.",
    "play_once": "The playback can only be started once.",
    "start_answer_id": "Answer IDs in the csv file will start with this number.",
    "questions": "Questions/Statements for the rows of the matrix.",
    "recording_name": "Custom name for recording, use 'id:' to refer to a preceding field (optional)",
    "button_fade": "Time in ms which a button visually stays pressed if applicable.",
    "randomize": "Randomize the order of the questions per participant.",
    "pupil_on_next": "Message/Annotation to send to pupil on page change.",
    "annotation": "Text for Pupil Core annotation. (default: test)",
    "randomization": "Method to randomize pages within groups",
    "randomization_file": "Path to a line-break separated comma separated list of orders.",
    "save_after": "Page to write to the results file at clicking next.",
    "image_position": "Placement of the image on the page.",
    "x_pos": "The left-right position of the top left corner of the image in pixels.",
    "y_pos": "The top-bottom position of the top left corner of the image in pixels.",
    "width": "The width of the image in pixels.",
    "height": "The height of the image in pixels.",
    "image_file": "The file of the image.",
    "address": "The OSC address to send to, should start with '/'.",
    "value": "The value to send over OSC, use 'id:' to refer to a preceding field.",
    "receiver": "IP and port of the OSC receiver to send to."
}

# question types and their fields
fields_per_type = {
    "HLine": [{"type": "QComboBox", "objectName": "QLineEdit"}],
    "Radio": [{"type": "QComboBox", "objectName": "QLineEdit", "id": "QLineEdit", "text": "QPlainTextEdit",
               "required": "QCheckBox", "answers": "QPlainTextEdit", "start_answer_id": "QLineEdit"}],
    "Check": [{"type": "QComboBox", "objectName": "QLineEdit", "id": "QLineEdit", "text": "QPlainTextEdit",
               "answers": "QPlainTextEdit"}],
    "Text": [{"type": "QComboBox", "objectName": "QLineEdit", "id": "QLineEdit", "text": "QPlainTextEdit",
              "required": "QCheckBox", "size": "QRadioButton", "policy": "QComboBox"}],
    "Slider": [{"type": "QComboBox", "objectName": "QLineEdit", "id": "QLineEdit", "text": "QPlainTextEdit",
                "required": "QCheckBox", "min": "QLineEdit", "max": "QLineEdit", "start": "QLineEdit",
                "labelled": "QCheckBox", "label": "QPlainTextEdit", "question_above": "QCheckBox",
                "header": "QPlainTextEdit"}],
    "Player": [{"type": "QComboBox", "objectName": "QLineEdit", "id": "QLineEdit", "required": "QCheckBox",
                "start_cue": "QLineEdit", "track": "QLineEdit", "video": "QLineEdit", "buttons": "QCheckBox",
                "pupil": "QLineEdit", "timer": "QLineEdit", "play_once": "QCheckBox"}],
    "MUSHRA": [{"type": "QComboBox", "objectName": "QLineEdit", "id": "QLineEdit", "required": "QCheckBox",
                "start_cues": "QLineEdit", "end_cues": "QLineEdit", "track": "QLineEdit", "xfade": "QCheckBox"}],
    "Button": [{"type": "QComboBox", "objectName": "QLineEdit", "id": "QLineEdit", "required": "QCheckBox",
                "inscription": "QLineEdit", "function": "QComboBox"}],
    "Plain Text": [{"type": "QComboBox", "objectName": "QLineEdit", "text": "QPlainTextEdit"}],
    "Password": [{"type": "QComboBox", "objectName": "QLineEdit", "id": "QLineEdit", "text": "QPlainTextEdit",
                 "required": "QCheckBox", "password_file": "QPushButton", "policy": "QComboBox"}],
    "ABX": [{"type": "QComboBox", "objectName": "QLineEdit", "id": "QLineEdit", "required": "QCheckBox",
            "start_cues": "QLineEdit", "track": "QLineEdit", "text": "QLineEdit",
             "answers": "QLineEdit", "button_texts": "QLineEdit", "x": "QCheckBox"}],
    "Matrix": [{"type": "QComboBox", "objectName": "QLineEdit", "id": "QLineEdit", "questions": "QPlainTextEdit",
               "required": "QCheckBox", "answers": "QPlainTextEdit", "start_answer_id": "QLineEdit",
                "randomize": "QCheckBox"}],
    "Image": [{"type": "QComboBox", "objectName": "QLineEdit", "image_file": "QPushButton", "image_position": "QComboBox",
               "width": "QLineEdit", "height": "QLineEdit"}],
    "OSCButton": [{"type": "QComboBox", "objectName": "QLineEdit", "id": "QLineEdit", "required": "QCheckBox",
                    "inscription": "QLineEdit", "receiver": "QComboBox", "address": "QLineEdit", "value": "QLineEdit"}]
        }
types = list(fields_per_type.keys())

policy_possibilities = ["None", "int", "double", "regex"]

function_possibilites = ["Annotate", "Recording", "Stop", "Calibration"]

player_buttons = ["Play", "Pause", "Stop"]

randomize_options = ["None", "balanced latin square", "from file"]

image_positions = ["here", "top", "bottom", "left", "right", "free"]

# page fields
page_fields = ["title", "description", "randomgroup", "pupil_on_next"]

# general questionnaire data / fields
general_fields = [
    "help_ip",
    "help_port",
    "help_text",
    "audio_ip",
    "audio_port",
    "audio_tracks",
    "video_ip",
    "video_port",
    "pupil_ip",
    "pupil_port",
    "go_back",
    "back_text",
    "forward_text",
    "save_after",
    "send_text",
    "answer_pos",
    "answer_neg",
    "save_message",
    "pagecount_text",
    "filepath_results",
    "delimiter",
    "stylesheet",
    "button_fade",
    "randomization",
    "randomization_file"
]

default_values = {
    "go_back": True,
    "back_text": "Zurück",
    "forward_text": "Weiter",
    "send_text": "Absenden",
    "answer_pos": "Ja",
    "answer_neg": "Nein",
    "save_message": "Sind Sie bereit den Fragebogen zu beenden und somit Ihre Angaben zu speichern?",
    "pagecount_text": "Seite {} von {}",
    "filepath_results": './results/results.csv',
    "delimiter": ';',
    "stylesheet": './stylesheets/minimal.qss',
    "audio_ip": "",
    "audio_port": "",
    "audio_tracks": "",
    "video_ip": "",
    "video_port": "",
    "pupil_ip": "",
    "pupil_port": "",
    "help_ip": "",
    "help_port": "",
    "help_text": "",
    "title": "",
    "id": "",
    "start_cue": "",
    "track": "",
    "start_cues": "",
    "end_cues": "",
    "text": "",
    "answers": "",
    "size": 1,
    "min": "",
    "max": "",
    "start": "",
    "labelled": False,
    "buttons": player_buttons,
    "policy": ["None"],
    "function": "Calibration",
    "inscription": "",
    "password_file": "",
    "button_texts": "",
    "x": False,
    "play_once": False,
    "start_answer_id": 0,
    "button_fade": 100,
    "randomize": False,
    "randomization": "None",
    #"save_after": None
    "randomization_file": "",
    "x_pos": "",
    "y_pos": "",
    "image_file": "",
    "width": "",
    "height": "",
    "image_position": "here",
    "receiver": [],
    "address": ""
    #"pupil_on_next": ''
}
